<template>
  <div>
    <div style="height: 1000px">
      <el-button @click="visible = true">三级交互</el-button>
    </div>
    <div
      :style="{
        position: 'absolute',
        left: 0,
        bottom: 0,
        right: 0,
        borderTop: '1px solid #e9e9e9',
        padding: '10px 20px',
        background: '#fff',
        textAlign: 'right'
      }"
    >
      <el-button :style="{marginRight: '8px'}" @click="onClose">取 消</el-button>
      <el-button @click="onClose" type="primary">提 交</el-button>
    </div>
    <BaseDialog :visible.sync="visible" destroyOnClose>
      <div>
        内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
        <br />内容...
      </div>
    </BaseDialog>
  </div>
</template>

<script>
export default {
  name: 'role',
  data() {
    return {
      visible: false
    };
  },
  methods: {
    onClose() {
      this.$emit('close', false);
    }
  }
};
</script>
